server:
  port: 8020
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
jpa:
  ribbon:
    NFLoadBalancerRuleClassName: com.springclound.configuration.NacosWeightedRule